### ISSUE TITLE
Live support does not seem to kick in when using FP load/play function

### ISSUE THREAD

**Issue by Ethorsen** [flowplayer/flowplayer-mpegdash#16]
If I load a FP instance with pre-defined clip/sources, and click on the instance or use toggle method, everything is working fine.  New MPD file is being downloaded when buffer is running low and live streaming is playing on forever.

But if I try to change the source of the instance by using api.play({new clip});  Only current MPD file is downloaded and played, thus ending the stream after only X sec.

**Comment by blacktrash** [comment]
Please provide a link to a *minimal!* sample page which demonstrates the problem.

**Comment by Ethorsen** [comment]
Here it is:
http://codepen.io/anon/pen/ZKGEEa

If you click right on the video to start it, it will play properly.  You can see the new manifest being downloaded every X sec or so.

If you click "Reload live stream" at the top, only initial manifest will be downloaded and video will end once every segment in it has been played.

Thx

**Comment by blacktrash** [comment]
Something specific to this stream. It stops after 30 seconds whenever autoplay is involved; you don't need to reload (which involves autoplay), a splash setup or configuring autoplay is sufficient to observer this.
With other streams this is not a problem.
Strange.

**Comment by Ethorsen** [comment]
This is a live Segmented timeline MPD file generated by Wowza.   I am personnaly using nginx-rtmp-module to generate the same kind of live manifest.  (using https://github.com/sergey-dryabzhinsky/nginx-rtmp-module)

I found a workaround for now, ugly but does the trick for all (but IE 11/Edge that doesnt seem to like it).

`}).on("ready", function (e, api, video) {
                    console.log("flowplayer ready.");

                     flowplayer().pause();
                     setTimeout(function() {
                        flowplayer().resume();
                     }, 20);
});`

**Comment by blacktrash** [comment]
That might not work on mobiles (lack of user interaction).

FWIW, the dash.if validator http://dashif.org/conformance.html says:
Segment timeline for type dynamic is not supported, only MPD will be tested.
