### ISSUE TITLE
Support encrypted streams

### ISSUE THREAD

**Issue by blacktrash** [flowplayer/flowplayer-mpegdash#3]
Problem will be to find/create a sample.

**Comment by RopoMen** [comment]
http://dashif.org/reference/players/javascript/v2.1.1/samples/dash-if-reference-player/app/sources.json

**Comment by blacktrash** [comment]
@RopoMen - sure, sure.
But did you get one to work at http://dashif.org/reference/players/javascript/v2.4.1/samples/dash-if-reference-player/ ? I didn't find one so far, probably one needs additional access data - or the streams are simply currently not available (happens quite a lot) or ...

**Comment by RopoMen** [comment]
Yeah :) 
Did only quickly look in to that and remembered this ticket. Seems to require also the license url, ofc.

I'm not sure if this could help https://docs.microsoft.com/en-us/azure/media-services/media-services-protect-with-drm 

I have used (5 years a go) this http://wmtap.smdisp.net/janus/summary.asp?#9_Series_Test_Cases
and from that remembered that Microsoft offers pretty good test contents and I think they may have even better test content for MPEG-DASH with DRM.

**Comment by RopoMen** [comment]
Actually here: http://playready.azurewebsites.net/Home/AdaptiveTests

```
Tears Of Steel Teaser 4K CENC (H264 AAC, CENC)

(c) Copyright Blender Foundation | mango.blender.org
Content Key Id	{6f651ae1-dbe4-4434-bcb4-690d1564c41c}
MPEG-DASH manifest	http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/manifest(format=mpd-time-csf)
```

**Comment by blacktrash** [comment]
But the sample player wants a license *URL* for playready (click on "Show Options").
As long as I don't see a stream working in the sample player, there's not much sense in attacking this, from my pov.

**Comment by RopoMen** [comment]
I noticed that, all non-encrypted streams worked ok.

This place contains also test drm server + test player.
http://playready.azurewebsites.net/Home/TestPlayer

**Comment by blacktrash** [comment]
@RopoMen - this is now implemented: http://demos.flowplayer.org/api/dash.html#drm

Setting of robustnessLevel must still be investigated, seems to depend on browser capabilities.

Docs for the 2 new `protection` and `protectionLevel` clip dash options to follow.

**Comment by blacktrash** [comment]
And I haven't found a stream which works in IE in the dash.js sample player, therefore so far it doesn't work in IE either.

**Comment by blacktrash** [comment]
Also does not work in desktop Safari (as in dash.if reference player) - this is bordering on an academic exercise ...

**Comment by blacktrash** [comment]
Implemented.
