### ISSUE TITLE
Flowplayer mpegdash: Video without Audio track crashed

### ISSUE THREAD

**Issue by Dream-Work** [flowplayer/flowplayer-mpegdash#9]
Browser: Chrome 46 (64-bit)
System: OSX
Player: Flowplayer 6.0.4 + mpegdash plugin

PLayer:  dash: Unsupported video
Console:  audioCodec (audio/mp4;codecs="unknown") is not supported.  

I would like to play videos which have no audio track.
Is it possible to control it by a parameter ?

thx

**Comment by blacktrash** [comment]
That looks like:
- your mpd has a broken codecs declaration or
- the format/codec is broken and leads to codecs="unknown" in your mpd

It's certainly not a problem with a missing audio track.
If you provide the URL of the mpd, I might be able to give a more precise diagnosis.

**Comment by blacktrash** [comment]
As per please https://github.com/flowplayer/flowplayer-mpegdash#stream-compatibility also test your stream first in the dash.js sample player at http://dashif.org/reference/players/javascript/v1.5.1/samples/dash-if-reference-player/ - if it does not play there, you may get more/better advice there as well; we will monitor that too, obviously.

Closing for now.
